`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 23.09.2025 09:24:59
// Design Name: 
// Module Name: IDDR
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 

//          this is a successful attempt to create a DDR LVDS module that consists of two always_ff - blocks
//          two always-ff blocks is inherently messy, which is why this module is such a mess.
//          it has been patched until it worked, but has not really been designed with a state machine in mind
//          alternatives to this approach would have been:

//          have a clock twice as fast as the LVDS clck, which can then trigger logic on the posedge only
//          this has the downside that it requires a very fast clock on the fpga: 500 Mhz for 250 MHz of LVDS clock rate.
//          i am pretty sure that the zedboards FPGA can not provide such a high clock rate, which is why I needed to design a logic that works on both edges of the clock
//          verilog doesnt allow something like: always_ff(@posedge clock OR negedge clock). so one has to have to always_ff blocks, one for posedge clock, one for negedge clock.
//          each always_ff block just registers the D signal at its edge of the C signal. in the end the two received data "halves" have to be zipped together with the right always_ff starting

//          Another way of doing it might have been: 
//          using IDDR blocks: these would take in the two data bits per C cycle and present them to the FPGA logic at the same time synchronously to one clock edge.
//          sady, i have only now understood this,  way after I made the "two alyways_ff blocks" method work

//          
//          this module works as follows:
//          each always-block checks wether it is the first to notice that a new frame of data is arriving.
//          they also shift their shift registers in and sample the data line if a frame of data is coming in
//          
//          in the end, bot these shift registers are "zipped" and the resulting long message is sent via the axi stream protocol.

//          currently there is no procedure in place for checking if tready is low.
//          if the axis FIFO is full we will simply miss this message, which is not a big deal. a warning will be generated by the fifo
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module DDR_Stream_to_AXI_Stream_IDDR
    #(parameter NUM_TRANSACTIONS = 16  // after how many transactions does the tlast signal assert?
     // parameter AXI_CLK_FACTOR = 4)  // how much slower should the axi be than the lvds clock?
     )
    (
    input wire enable,
    input wire [5:0] msglen, //sum of gpx2's stop_data_bitwidth and refindex_bitwidth
    input wire aresetn,
    input wire C_i, // LVDS clock
    input wire D, //LVDS data. this is actually a delayed signal. an IDELAYE2 instance delays the signal with a programmable amount wrt the C signal
    input wire F,  //LVDS frame. the frame signals the start of an LVDS message. this is actually a delayed signal. an IDELAYE2 instance delays the signal with a programmable amount wrt the C signal
    
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 AXIS TREADY" *)
    (* X_INTERFACE_PARAMETER = "FREQ_HZ 100000000" *)
    input wire tready,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 AXIS TDATA" *)
    output reg [63:0] tdata_delayed,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 AXIS TVALID" *)
    output reg tvalid_delayed,
    (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 AXIS TLAST" *)
    output reg tlast_delayed
  //  output wire axi_clk
    );

localparam TRANSACTION_COUNTER_WIDTH = $clog2(NUM_TRANSACTIONS);
localparam TDATA_WIDTH = 64;
localparam COUNTER_WIDTH = $clog2(TDATA_WIDTH);
//localparam SHIFT_REG_WIDTH = 
//localparam CLK_COUNTER_WIDTH = $clog2(AXI_CLK_FACTOR);

//reg tvalid;
//reg tlast;
//reg [63:0] tdata;
reg [TRANSACTION_COUNTER_WIDTH-1:0] transaction_counter;  //for the tlast signal
//reg [COUNTER_WIDTH-1:0] bit_counter;  //for counting to message_length in one photon event: x bits for refindex and y bits for stop result
wire [63:0] tdata_posedge_first;
reg counter_enabled;
wire [63:0] tdata_mask;
reg [31:0] posedge_Qs;
reg [31:0] negedge_Qs;
reg F_old, F_old_old;

reg tvalid;
reg tlast;
reg[63:0] tdata;
reg [63:0] shift_register;
reg shift_register_in;
reg Q1_F_old;
//reg [CLK_COUNTER_WIDTH-1:0] axi_clk_counter;

//TODO: figure out how to properly route the clock signal
BUFG BUFG_inst (
   .O(C), // 1-bit output: Clock output
   .I(C_i)  // 1-bit input: Clock input
);



IDDR #(
   .DDR_CLK_EDGE("SAME_EDGE_PIPELINED"), // "OPPOSITE_EDGE", "SAME_EDGE"
                                   //    or "SAME_EDGE_PIPELINED"
   .INIT_Q1(1'b0), // Initial value of Q1: 1'b0 or 1'b1
   .INIT_Q2(1'b0), // Initial value of Q2: 1'b0 or 1'b1
   .SRTYPE("SYNC") // Set/Reset type: "SYNC" or "ASYNC"
) IDDR_D (
   .Q1(Q1_D), // 1-bit output for positive edge of clock
   .Q2(Q2_D), // 1-bit output for negative edge of clock
   .C(C),   // 1-bit clock input
   .CE(enable), // 1-bit clock enable input
   .D(D),   // 1-bit DDR data input
   .R(1'b0),   // 1-bit reset
   .S(1'b0)    // 1-bit set
);

IDDR #(
   .DDR_CLK_EDGE("SAME_EDGE_PIPELINED"), // "OPPOSITE_EDGE", "SAME_EDGE"
                                   //    or "SAME_EDGE_PIPELINED"
   .INIT_Q1(1'b0), // Initial value of Q1: 1'b0 or 1'b1
   .INIT_Q2(1'b0), // Initial value of Q2: 1'b0 or 1'b1
   .SRTYPE("SYNC") // Set/Reset type: "SYNC" or "ASYNC"
) IDDR_F (
   .Q1(Q1_F), // 1-bit output for positive edge of clock
   .Q2(Q2_F), // 1-bit output for negative edge of clock
   .C(C),   // 1-bit clock input
   .CE(enable), // 1-bit clock enable input
   .D(F),   // 1-bit DDR data input
   .R(1'b0),   // 1-bit reset
   .S(1'b0)    // 1-bit set
);



        
//we assume that the msb is always sent on a posedge of C

always @(posedge C, negedge aresetn) begin
        if (!aresetn) begin
            posedge_Qs <= 0;
            negedge_Qs <= 0;
           // F_old <= 0;
           // F_old_old <= 0;
            transaction_counter <= NUM_TRANSACTIONS-1;
            //bit_counter <= msglen/2-1;  //must be stable before reset. software is responsible for writing correct value here.
            counter_enabled <= 0;
            tvalid <= 0;
            tlast <= 0;
            tdata <= 0;
            tvalid_delayed <= 0;
            tlast_delayed <= 0;
            tdata_delayed <= 0;
            shift_register <= 0;
            shift_register_in <= 0;
            Q1_F_old <= 0;
        end
        else begin     
            //default statements:
           // if(!axi_clk_counter) begin
                tvalid <= 0;
                tlast <= 0;
            //end else begin
             //   axi_clk_counter <= axi_clk_counter -1;
            //end
        
          //  F_old <= F;
          //  F_old_old <= F_old;
            

        
            posedge_Qs <= {posedge_Qs[30:0], Q1_D};
            negedge_Qs <= {negedge_Qs[30:0], Q2_D};
            tdata <= tdata_posedge_first;

            if(counter_enabled) begin
                shift_register <= {shift_register[62:0], shift_register_in};
                //bit_counter <= bit_counter -1;
            end
            //if (!bit_counter) begin
            if (shift_register[msglen/2-2] == 1) begin
                counter_enabled <= 0;
                //bit_counter <= msglen/2-1;
                //tdata <= tdata_posedge_first&tdata_mask;
                //just always enable counter?reset it when new frame arrives?
                //removed mask already. pipeline the mask register? yes thats smart
                
                tvalid <= 1;
                //axi_clk_counter <= AXI_CLK_FACTOR - 1;
                //counter_enabled <= 0;
                transaction_counter <= transaction_counter -1;
                if (!transaction_counter) begin
                    tlast <= 1'b1;
                    transaction_counter <= NUM_TRANSACTIONS-1;
                end
            end
                

            //end
            //if(Q1_F&!Q2_F) begin
            //    counter_enabled <= 1;
            //end
            
            //if (counter_enabled&(bit_counter == (msglen/2-1))) begin
                tvalid_delayed <= tvalid;
                tdata_delayed <= tdata & tdata_mask;  //pipelining to meet timing requirements of fast lvds clock
                tlast_delayed <= tlast;
                
            //end
            Q1_F_old <= Q1_F;
            if(Q1_F & !Q1_F_old) begin
                //bit_counter <= msglen/2-1;
                counter_enabled <= 1;
                shift_register_in <= 1;
            end else begin
                shift_register_in <= 0;
            end
            

            
        end
end



// Zip the words when the first data bit was on a posedge of the clock
zip_words zipper_posedge_first (
    .word1(posedge_Qs),
    .word2(negedge_Qs),
    .result(tdata_posedge_first)
);

/*
// without this delay, the AXI stream fifo is not ready to accept the axi stream data yet
delay_by_X_clocks delay_tvalid (
    .data_in(tvalid),
    .data_out(tvalid_delayed),
    .clk(C),
    .aresetn(aresetn)
);             

delay_by_X_clocks delay_tlast (
    .data_in(tlast),
    .data_out(tlast_delayed),
    .clk(C),
    .aresetn(aresetn)
);    

delay_64bit_by_X_clocks delay_tdata (
    .data_in(tdata),
    .data_out(tdata_delayed),
    .clk(C),
    .aresetn(aresetn)
);   

*/
// a helper function to generate a mask, eg generates 0x00000007 for X = 3
function [64-1:0] gen_mask(input [64-1:0] X);
    gen_mask = (1 << X) - 1;
endfunction

assign tdata_mask = gen_mask(msglen);
 

endmodule
              
//zip the words with msb of word1 becoming the msb of the result
module zip_words (
    input wire [31:0] word1,  // First 32-bit word
    input wire [31:0] word2,  // Second 32-bit word
    output reg [63:0] result  // Resulting 64-bit word
);
    integer i;
    always @(*) begin
        for (i = 0; i < 32; i = i + 1) begin
            result[2*i]   = word2[i];  // Even bits: word2
            result[2*i+1] = word1[i];  // Odd bits: word1
        end
    end
    
    

    
    
endmodule




// delay axi stream, so that fifo can assert tready before tvalid arrives:

//module delay_64bit_by_X_clocks (
//    input wire clk,          // Clock signal
//    input wire aresetn,        // Active-high reset
//    input wire [63:0] data_in,  // 64-bit input signal
//    output reg [63:0] data_out  // 64-bit output signal (delayed by 60 cycles)
//);

// Parameter for the number of delay cycles
//parameter DELAY_CYCLES = 60;       // Default delay is 60 cycles. try to reduce this

// X-stage shift register for 64-bit data
//reg [63:0] shift_reg [DELAY_CYCLES-1:0];  // Array of 60 64-bit registers

//integer i;
//always @(posedge clk or negedge aresetn) begin
//    if (!aresetn) begin
 //       // Asynchronously clear all stages
  //      for (i = 0; i < DELAY_CYCLES; i = i + 1) begin
   //         shift_reg[i] <= 64'b0;
    //    end
     //   data_out <= 64'b0;
   // end else begin
        // Shift the data through the register
     //   shift_reg[DELAY_CYCLES-1] <= data_in;  // New data goes into the last stage
     //   for (i = DELAY_CYCLES-2; i >= 0; i = i - 1) begin
     //       shift_reg[i] <= shift_reg[i + 1];  // Shift data to the next stage
     //   end
     //   data_out <= shift_reg[0];  // Output the oldest value
  //  end
//end

//endmodule

/*
module delay_by_X_clocks (
    input wire clk,        // Clock signal
    input wire aresetn,      // Active-high reset
    input wire data_in,    // Input signal to be delayed
    output reg data_out    // Output signal (delayed by 60 cycles)
);
// Parameter for the number of delay cycles
parameter DELAY_CYCLES = 60;       // Default delay is 60 cycles
// Shift register to delay the signal by 60 cycles
reg [DELAY_CYCLES-1:0] shift_reg;     // 60-stage shift register

always @(posedge clk or negedge aresetn) begin
    if (!aresetn) begin
        // Asynchronous reset: clear all stages
        shift_reg <= 0;
        data_out <= 1'b0;
    end else begin
        // Shift the data through the register
        shift_reg <= {data_in, shift_reg[DELAY_CYCLES-1:1]};
        data_out <= shift_reg[0];  // Output the oldest value
    end
end

endmodule
*/